### ISSUE TITLE
pip installing this package is still using django.utils import six 

### ISSUE THREAD

**Issue by Connotating** [percipient/django-querysetsequence#62] opened 2019-12-10 19:05 UTC
when installed with pip, in the __init__ file of the package there is still an import from django.utils import six; it is not compatible with django 3.0+

**Comment by clokep** [comment] 2019-12-10 19:37
This is a duplicate of #58. A new release with support for Django 3 has not been released yet.

**Closed by clokep** 2019-12-10 19:37 UTC
